name: CI

on: [push]

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    EC2_HOST: ${{ secrets.EC2_HOST }}
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
  
        - name: Setup Node.js
          uses: actions/setup-node@v4
  
        - name: Install Dependencies and Build Frontend
          run: |
            cd frontend
            npm install
            npm run build
            ls -la
  
    upload_to_s3:
      name: Upload to S3
      needs: build
      runs-on: ubuntu-latest
  
      steps:
        - name: Upload to S3
          run: |
            aws --version
            cd frontend/dist/frontend/browser
            ls -la
            aws s3 sync frontend/build s3://$AWS_S3_BUCKET/ --recursive --acl public-read

    build_and_deploy_backend:
        name: Build and Deploy Backend
        runs-on: ubuntu-latest
            
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4 
        
        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: $DOCKER_USERNAME
            password: $DOCKER_TOKEN
        - name: Build and push backend Docker image
          run: |
              docker build -t $DOCKER_USERNAME/backend-image:${{ github.run_number }} .
              docker push $DOCKER_USERNAME/backend-image:${{ github.run_number }}
              docker tag $DOCKER_USERNAME/backend-image:${{ github.run_number }} ${{ secrets.DOCKER_USERNAME }}/backend-image:latest
              docker push $DOCKER_USERNAME/backend-image:latest

        - name: Install Docker on EC2
          run: |
            echo "$SSH_PRIVATE_KEY" > ./private_key.pem
            chmod 600 ./private_key.pem
            ssh -i ./private_key.pem -o StrictHostKeyChecking=no $EC2_HOST "
            sudo yum update -y
            sudo yum install -y docker
            sudo service docker start
            sudo docker run -d -p 80:5000 $DOCKER_USERNAME/backend-image:latest
            "